name: Build
on:
  pull_request:
    branches: [ main ]
jobs:
  test-app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      # - name: Start server in the background
      #   run: npm start &
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          working-directory: app
          build: npm run build
          wait-on: http://0.0.0.0:3000

  build-app:
    needs: test-app
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build docker image
        run: docker build .
