name: Build
on:
  pull_request:
    branches: [ main ]
defaults:
  run:
    working-directory: app
jobs:
  build-app:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build docker image
        run: docker build .
