name: Build
on:
  pull_request:
    branches: [ main ]
jobs:
  test-app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
  build-app:
    needs: test-app
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - name: debug
        run: echo $(pwd)
      - name: Build docker image
        run: docker build .
